djangoecommerce/catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
]

djangoecommerce/urls.py
# from django.contrib import admin
# from django.urls import path
# from .core import views 

# urlpatterns = [
# 	 path('', views.home, name='home'),
#     path('admin/', admin.site.urls),
# ]

from django.conf.urls import url
from django.urls import include
from django.contrib import admin
from .core import views

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
#     url(r'^contato/$', views.contact, name='contact'),
#     url(r'^produto/$', views.product, name='product'),
#     url(r'^produtos/$', views.product_list, name='product_list'),
#     url(r'^admin/', admin.site.urls),
# ]


# urlpatterns = [
#     url(r'^$', views.index, name='index'),
#     url(r'^produtos/', include('djangoecommerce.catalog.urls', namespace='catalog')),
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^catalogo/', include('djangoecommerce.catalog.urls', namespace='catalog')),
    url(r'^admin/', admin.site.urls),
]

djangoecommerce/catalog/models.py
from django.db import models
# from django.core.urlresolvers import reverse
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('nome', max_length=100)
    slug = models.SlugField('identificador', max_length=100)
    created = models.DateTimeField('criado em', auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):
    name = models.CharField('nome', max_length=100)
    slug = models.SlugField('identificador', max_length=100)
    category = models.ForeignKey('Category', verbose_name='categoria', on_delete=models.CASCADE)
    description = models.TextField('descrição', blank=True)
    price = models.DecimalField('preço', decimal_places=2, max_digits=8)
    created = models.DateTimeField('criado em', auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now=True)

    class Meta:
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
        # return reverse('catalog:product', kwargs={'slug': self.slug})

djangoecommerce/core/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField('nome', max_length=100)
    email = models.EmailField('e-mail', max_length=50)
    message = models.TextField('mensagem')

    class Meta:
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'
        ordering = ['name', ]

    def __str__(self):
        return self.name

djangoecommerce/core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string

from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

    def send_mail(self):
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        }

        body = render_to_string('email.txt', context=context)

        send_mail(
            'Contato do Django E-Commerce', body, self.cleaned_data['email'],
            [self.cleaned_data['email'], settings.DEFAULT_FROM_EMAIL]
        )

djangoecommerce/catalog/views.py
from django.shortcuts import render
from .models import Product, Category


def product_list(request):
    context = {
        'product_list': Product.objects.all()
    }
    return render(request, 'catalog/product_list.html', context)


def category(request, slug):
    current_category = Category.objects.get(slug=slug)
    products_list = Product.objects.filter(category=current_category)

    context = {
        'current_category': current_category,
        'products_list': products_list,
    }
    return render(request, 'catalog/category.html', context)


def product(request, slug):
    context = {
        'product': Product.objects.get(slug=slug)
    }
    return render(request, 'catalog/product.html', context)

djangoecommerce/core/views.py
from django.shortcuts import render
from .forms import ContactForm


def index(request):
    return render(request, 'index.html')


def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        form.send_mail()
        success = True
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

djangoecommerce/catalog/templates/catalog/category.html
{% extends "base.html" %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>{{ current_category }}</h1>
    </div>
    <div class="row">
        {% for product in products_list %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="http://placehold.it/350x250" alt=""/>
                    </a>
                    <div class="caption">
                        <h3>{{ product.name }}</h3>
                        {{ product.description|linebreaks }}
                        <p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Button</a>
                            <a href="#" class="btn btn-default" role="button">Button</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangoecommerce/catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title %}
    {{ product.name }} | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>{{ product.name }}</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <a href="{{ product.get_absolute_url }}" class="thumbnail">
                <img src="http://placehold.it/350x250" alt=""/>
            </a>
        </div>
        <div class="col-sm-8">
            {{ product.description|linebreaks }}
        </div>
    </div>
{% endblock %}

djangoecommerce/catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>Produtos</h1>
    </div>
    <div class="row">
        {% for product in product_list %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="http://placehold.it/350x250" alt=""/>
                    </a>
                    <div class="caption">
                        <h3>{{ product.name }}</h3>
                        {{ product.description|linebreaks }}
                        <p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Button</a>
                            <a href="#" class="btn btn-default" role="button">Button</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangoecommerce/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django E-Commerce{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen"/>
</head>
<body>
{% include 'includes/navbar.html' %}
<div class="container">
    {% block container %}
    {% endblock %}
    {% include 'includes/footer.html' %}
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

djangoecommerce/core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>Fale conosco</h1>
        {% if success %}
            <div class="alert alert-success text-center">
                Mensagem enviada com sucesso
            </div>
        {% endif %}
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                        <div class="col-md-9">
                            {% render_field field class='form-control' %}
                            {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

djangoecommerce/core/templates/includes/footer.html
<footer>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-unstyled">
                <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
                <li><a href="">Início</a></li>
                <li><a href="">Produtos</a></li>
                <li><a href="">Contato</a></li>
                <li><a href="">Termos e Privacidade</a></li>
            </ul>
        </div>
    </div>
</footer>

djangoecommerce/core/templates/includes/navbar.html
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'index' %}" class="navbar-brand">Django E-Commerce</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'index' %}">Início</a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"
                       href="{% url 'catalog:product_list' %}" id="download">Categorias
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="download">
                        {% for category in categories %}
                            <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    <a href="{% url 'contact' %}">Contato</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Minha Conta</a></li>
            </ul>
        </div>
    </div>
</div>

djangoecommerce/core/templates/index.html
{% extends "base.html" %}

{% block container %}
    <div class="jumbotron page-header">
        <h1>Django E-Commerce</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.</p>
        <p><a class="btn btn-primary">Saiba mais</a></p>
    </div>
{% endblock %}

djangoecommerce/core/templates/master.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django E-Commerce{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen"/>
</head>
<body>
    {% include 'includes/navbar.html' %}
    <div class="container">
        {% block container %}
        {% endblock %}
        {% include 'includes/footer.html' %}
    </div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

djangoecommerce/core/templates/product.html
{% extends "master.html" %}

{% block title %}
    Produto | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>Página do Produto</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <a href="#" class="thumbnail">
                <img src="http://placehold.it/350x250" alt=""/>
            </a>
        </div>
        <div class="col-sm-8">
            <dl>
                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>
                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>
                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>
                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>
                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>
            </dl>
        </div>
    </div>
{% endblock %}

djangoecommerce/core/templates/product_list.html
{% extends "master.html" %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>Produtos</h1>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="#">
                    <img src="http://placehold.it/350x250" alt=""/>
                </a>
                <div class="caption">
                    <h3>Lorem ipsum dolor sit amet</h3>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.</p>
                    <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                       role="button">Button</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="#">
                    <img src="http://placehold.it/350x250" alt=""/>
                </a>
                <div class="caption">
                    <h3>Lorem ipsum dolor sit amet</h3>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.</p>
                    <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                       role="button">Button</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="#">
                    <img src="http://placehold.it/350x250" alt=""/>
                </a>
                <div class="caption">
                    <h3>Lorem ipsum dolor sit amet</h3>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.</p>
                    <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                       role="button">Button</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}